from telethon import events
import random, re
from userbot.utils import admin_cmd
import asyncio


@borg.on(admin_cmd("fbanbisi ?(.*)"))
async def _(event):
    if event.fwd_from:
        return
    FBAN = event.pattern_match.group(1)
    chat = await event.get_chat()
    if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await borg.send_message(chat, f"/start")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 88c4a4fe-4a8a-4880-87d5-d83554455918")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed a26a769d-616f-486f-b89f-fac0cb0a5c11")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 37708662-274e-4264-a61f-26ce50fcacda")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ca91a4e6-d6fa-4209-b8b1-6584d8f1dbf3")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed 8eb707da-3894-4611-8766-48d408324969")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed a4bcd10a-8f14-4bf3-9226-13fb873a0316")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 0b3371e6-0b20-4fb6-9285-6689aa9035aa")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed b65416ba-6b72-487a-8cf9-0d9b857cd234")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed 54cef9da-112c-4d63-9fa0-dc0fb3ced3fd")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 76f8fd60-1745-410a-975b-a021ce6da365")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed abe54d90-d67a-4ce8-afbc-0cd827084ecf")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5fcbde53-88cb-40a9-916f-f04223476663")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed c06a32d6-c9b9-4840-91e9-29b4de14ceff")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed e1c0cf1f-220a-46bb-b508-46eb6b1ecf55")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 8feb6ad8-1655-4dbc-9dc4-3d0546a3c1e1")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5d47a47c-9ee1-405b-bb33-d4cadfd0c102")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed a3048abf-43d1-4291-a92e-822e883b2ae0")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 924e05f0-2c93-4a81-a91a-a9cb4ff1993c")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 0e32f678-9c5f-47d5-b512-a3a607f1fd99")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 7389172d-b5ad-42bb-80af-5d0b50605390")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed 1f1cc20a-9f44-43ec-b2c0-9a4713b4fddb")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ca7a9f6e-3316-431c-b6d8-4bb929922bc4")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed f0321efe-83d3-4dde-aef0-fdb36df5bc50")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5e9e0a69-15cb-4998-bbd0-4e782ba8b649")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed 52ad135b-a917-4d08-9d9d-d7adca31d4ac")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed b71af67b-c39b-4606-b7ae-6de20880229a")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed a9e59bba-5725-45a4-82f0-95412986f838")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed e3e97adc-9e83-43a7-abf8-b2839ab4481f")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed fc7d5b2b-fbde-47ad-b11a-8d6edaaeb69f")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed dc8fccc6-5505-4337-afe8-26843bc899fa")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 84a464bb-61f5-49e9-b8b7-90d321fe458e")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed f665c8c9-9502-4e1b-9dc7-64337de00bfc")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/fban {FBAN}")
        await asyncio.sleep(3)
        await asyncio.sleep(100)


@borg.on(admin_cmd("unfbanbisi ?(.*)"))
async def _(event):
    if event.fwd_from:
        return
    UNFBAN = event.pattern_match.group(1)
    chat = await event.get_chat()
    if not event.text[0].isalpha() and event.text[0] not in ("/", "#", "@", "!"):
        await borg.send_message(chat, f"/start")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 88c4a4fe-4a8a-4880-87d5-d83554455918")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed a26a769d-616f-486f-b89f-fac0cb0a5c11")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 37708662-274e-4264-a61f-26ce50fcacda")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ca91a4e6-d6fa-4209-b8b1-6584d8f1dbf3")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed 8eb707da-3894-4611-8766-48d408324969")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed a4bcd10a-8f14-4bf3-9226-13fb873a0316")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 0b3371e6-0b20-4fb6-9285-6689aa9035aa")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed b65416ba-6b72-487a-8cf9-0d9b857cd234")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed 54cef9da-112c-4d63-9fa0-dc0fb3ced3fd")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 76f8fd60-1745-410a-975b-a021ce6da365")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed abe54d90-d67a-4ce8-afbc-0cd827084ecf")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5fcbde53-88cb-40a9-916f-f04223476663")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed c06a32d6-c9b9-4840-91e9-29b4de14ceff")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed e1c0cf1f-220a-46bb-b508-46eb6b1ecf55")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 8feb6ad8-1655-4dbc-9dc4-3d0546a3c1e1")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5d47a47c-9ee1-405b-bb33-d4cadfd0c102")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed a3048abf-43d1-4291-a92e-822e883b2ae0")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 924e05f0-2c93-4a81-a91a-a9cb4ff1993c")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 0e32f678-9c5f-47d5-b512-a3a607f1fd99")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 7389172d-b5ad-42bb-80af-5d0b50605390")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed 1f1cc20a-9f44-43ec-b2c0-9a4713b4fddb")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed ca7a9f6e-3316-431c-b6d8-4bb929922bc4")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed f0321efe-83d3-4dde-aef0-fdb36df5bc50")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 5e9e0a69-15cb-4998-bbd0-4e782ba8b649")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed 52ad135b-a917-4d08-9d9d-d7adca31d4ac")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed b71af67b-c39b-4606-b7ae-6de20880229a")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed a9e59bba-5725-45a4-82f0-95412986f838")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed e3e97adc-9e83-43a7-abf8-b2839ab4481f")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(30)
        await borg.send_message(chat, "/joinfed fc7d5b2b-fbde-47ad-b11a-8d6edaaeb69f")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed dc8fccc6-5505-4337-afe8-26843bc899fa")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed 84a464bb-61f5-49e9-b8b7-90d321fe458e")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await borg.send_message(chat, "/joinfed f665c8c9-9502-4e1b-9dc7-64337de00bfc")
        await asyncio.sleep(3)
        await borg.send_message(chat, f"/unfban {UNFBAN}")
        await asyncio.sleep(3)
        await asyncio.sleep(100)
